### PR TITLE
Support for SIMCOM A76xx Series. (IDFGH-9964)

### PR DESCRIPTION
**Pull request by diplfranzhoepfinger**

### CODE REVIEW

**Comment by diplfranzhoepfinger** [comment]
@david-cermak this is Modem as well.

**Comment by franz-ms-muc** [comment]
> ready to merge?

no. find the latest working one here: 

https://github.com/diplfranzhoepfinger/esp-protocols-tree-master-components-esp_modem-examples-simple_cmux_client/tree/feature/URC-Handler/simple_cmux_client/components/A7672_gnss

**Comment by franz-ms-muc** [comment]
this PR need a "modem" lable.

**Comment by diplfranzhoepfinger** [comment]
> @diplfranzhoepfinger Seeing all the changes

cool ideas. i will have a look.

**Comment by diplfranzhoepfinger** [comment]
> @diplfranzhoepfinger Seeing all the changes

cool ideas. i will have a look.

**Comment by diplfranzhoepfinger** [comment]
this is obsolete now, as A7672 is already supported by esp-modem.

**Pull request closed without merging**
