### PR TITLE
feat(modem): A7672_gnss (IDFGH-10176)

### PR DESCRIPTION
**Pull request by diplfranzhoepfinger**
feat(modem): A7672_gnss

### CODE REVIEW

**Comment by diplfranzhoepfinger** [comment]
2nd Try for #264

**Comment by diplfranzhoepfinger** [comment]
@david-cermak why does it skip all Checks ?

**Comment by david-cermak** [comment]
> why does it skip all Checks ?

The CI now checks for labels, as we have many other components, so we run it selectively. Have added `modem` label.

**Comment by diplfranzhoepfinger** [comment]
> > why does it skip all Checks ?
> 
> The CI now checks for labels, as we have many other components, so we run it selectively. Have added `modem` label.

coool . THAT is the Reason.

**Comment by diplfranzhoepfinger** [comment]
> > why does it skip all Checks ?
> 
> The CI now checks for labels, as we have many other components, so we run it selectively. Have added `modem` label.

but only @david-cermak can add Lables ? not the Comitter ?

**Comment by diplfranzhoepfinger** [comment]
so, the Error say that it does not Compile with ESP-IDF 4.3 . i will test that based on my Sample: 
https://github.com/diplfranzhoepfinger/esp-protocols-tree-master-components-esp_modem-examples-simple_cmux_client
and based on esp-idf-v4.3.5

OK?

**Comment by diplfranzhoepfinger** [comment]
on my Desk this Branch: 
https://github.com/diplfranzhoepfinger/esp-protocols-tree-master-components-esp_modem-examples-simple_cmux_client/tree/feature/esp-idf-v4.3.5
compiles with 
Build complete (0 errors, 0 warnings)

**Comment by david-cermak** [comment]
Thanks again for posting this change, but this looks like a copy-paste of the `sim7070_gnss` component. Is there anything else I'm maybe missing?

**Comment by david-cermak** [comment]
Let me close this for now, as it really looks like a hard copy of `sim7070_gnss`. we need to find a better way of adding another device...

**Comment by diplfranzhoepfinger** [comment]
Agree.

**Comment by diplfranzhoepfinger** [comment]
we switched to your USB Branch für SIMCOM A7672E, so this all is no more Maintained.

**Pull request closed without merging**
