### PR TITLE
feat(esp_modem): example add esp32p4 usb support (IDFGH-12673)

### PR DESCRIPTION
**Pull request by leeebo**
1. support ec20 cat.4 module in example modem_console and pppos_client
2. support esp32p4 in example modem_console and pppos_client

Block by https://github.com/espressif/esp-usb/pull/42

### CODE REVIEW

**Review by david-cermak — APPROVED** [review]
Changes in this PR LGTM!

@leeebo Could we merge it, or is this still WIP?

**Comment by leeebo** [comment]
Hi @david-cermak Thanks for your review, this MR is blocked by https://github.com/espressif/esp-usb/pull/30, I will finish the test work ASAP.

**Comment by david-cermak** [comment]
@leeebo this still LGTM,

could we merge it now or wait for the https://github.com/espressif/esp-usb/pull/44 ?

**Comment by david-cermak** [comment]
BTW (already told Tomas), the know issue section indicated in 

https://github.com/espressif/esp-usb/blob/master/host/class/cdc/esp_modem_usb_dte/CHANGELOG.md?plain=1#L8-L9

could be perhaps solved (worked around)  by this option

https://github.com/espressif/esp-protocols/blob/master/components/esp_modem/Kconfig#L19C12-L28

**Comment by leeebo** [comment]
Hi @david-cermak , let's just merge this PR, as `1.2.1` is  compatible with `^1.2.0`

**Comment by leeebo** [comment]
Hi @david-cermak , it should be ready to merge now. It doesn't need to wait as `^1.2.0` is compatible with `1.2.1`

**Review by david-cermak — APPROVED** [review]

**Pull request merged**
