### PR TITLE
Update esp_modem_command_library.cpp (IDFGH-9018)

### PR DESCRIPTION
**Pull request by franz-ms-muc**
AT+IFC=2,2 instead AT+IFC=2, 2

### CODE REVIEW

**Review by david-cermak — APPROVED** [review]
Thanks for the fix!

**Comment by franz-ms-muc** [comment]
courios: on a SIM7070 it is running with the old version, but a **A7672E** (**FASE**) was failing, and only running without the space.

**Comment by franz-ms-muc** [comment]
courios: on a SIM7070 it is running with the old version, but a **A7672E** (**FASE**) was failing, and only running without the space.

**Comment by david-cermak** [comment]
> courios: on a SIM7070 it is running with the old version, but a **A7672E** (**FASE**) was failing, and only running without the space.

That's probably the reason why it slipped though (as I was apparently testing it with 7600 or similar which accepts the space). Thanks!

**Pull request merged**
