### PR TITLE
Feature/extend example modem console (IDFGH-8394)

### PR DESCRIPTION
**Pull request by diplfranzhoepfinger**
https://github.com/espressif/esp-protocols/pull/145 proposes configurable Flow Control.

### CODE REVIEW

**Comment by diplfranzhoepfinger** [comment]
Removed this unused Config Parameters @tore-espressif

**Comment by tore-espressif** [comment]
@diplfranzhoepfinger thank you for the follow-up, LGTM!

**Comment by david-cermak** [comment]
LGTM, too, but please cleanup the commit history

**Review by david-cermak — CHANGES_REQUESTED** [review]
Please rebase (or simply drop all commits, but the [last one -- cb6a842](https://github.com/espressif/esp-protocols/pull/148/commits/cb6a842a0dc02bc091aac937b20d449d55fefe1e)

**Comment by diplfranzhoepfinger** [comment]
> Please rebase (or simply drop all commits, but the [last one -- cb6a842](https://github.com/espressif/esp-protocols/pull/148/commits/cb6a842a0dc02bc091aac937b20d449d55fefe1e)

you mean merge the History ?

**Comment by diplfranzhoepfinger** [comment]
ahhhhhhhhhhh understood. all is already merged, except the 1 File.

**Comment by diplfranzhoepfinger** [comment]
done in https://github.com/espressif/esp-protocols/pull/149

**Pull request closed without merging**
