### PR TITLE
Feature/integrate-modem (IDFGH-9797)

### PR DESCRIPTION
**Pull request by jamesrob4**

### CODE REVIEW

**Comment by f-hoepfinger-hr-agrartechnik** [comment]
[jamesrob4](https://github.com/jamesrob4) you must sign the CLA!

**Comment by 0xFEEDC0DE64** [comment]
@jamesrob4 are you still alive?

**Comment by diplfranzhoepfinger** [comment]
@areabow can you please ping your Colleague

**Comment by diplfranzhoepfinger** [comment]
@anjathiart please ping him.

**Pull request closed without merging**
