### PR TITLE
[modem]: Fix arguments names when spawn esp_modem_xxx declarations (IDFGH-13729)

### PR DESCRIPTION
**Pull request by embedcat**
## Description

This PR fixes arguments names which auto-declared by `DECLARE_ALL_COMMAND_APIS()` (`"include/generate/esp_modem_command_declare.inc"`).

For example, it would be:
`esp_err_t esp_modem_send_sms(esp_modem_dce_t *dce, const char *number, const char *message);`
instead of:
`esp_err_t esp_modem_send_sms(esp_modem_dce_t *dce, const char *p1, const char *p2);`

Also, it does clear auto completions and tips in IDE (VS Code + ESP-IDF):

### CODE REVIEW

**Review by david-cermak — APPROVED** [review]
Thanks for this fix, very helpful for C-API users!

Could you just clean the commit history, please? There're two separate commits + one merge commit, I'd be great if you can push it as a single commit only (then that commit message can be used to generate CHANGELOG).

**Comment by embedcat** [comment]
Oh sorry, I very confused with cleaning up commits. For now I am not able to do it.. Can I close this PR and do a new one with proper commit history?

**Comment by david-cermak** [comment]
> Oh sorry, I very confused with cleaning up commits. For now I am not able to do it.. Can I close this PR and do a new one with proper commit history?

of course, feel free to close this and create a new one with clean history.

Also, if you're having any further trouble with updating history, just let me know and I'll fix it and push your changes separately (the commit would be still attributed to you, just pushed by me)

**Comment by embedcat** [comment]
Reopen #654

**Pull request closed without merging**
