### PR TITLE
[mdns]: send PTR query for mdns browse when interface is ready (IDFGH-13841)

### PR DESCRIPTION
**Pull request by gytxxsy**
## Description

When an interface changes from not ready to ready, a PTR query should be sent for all mdns browse on that interface.

## Checklist

Before submitting a Pull Request, please ensure the following:

- [x] 🚨 This PR does not introduce breaking changes.
- [x] All CI checks (GH Actions) pass.
- [x] Documentation is updated as needed.
- [ ] ~~Documentation is updated as needed.~~ (no functional change)
- [ ] ~~Tests are updated or added as necessary.~~(no functional change)
- [x] Git history is clean — commits are squashed to the minimum necessary.

### CODE REVIEW

**Comment by gytxxsy** [comment]
@david-cermak Could you please take a look of this PR?

**Comment by david-cermak** [comment]
@gytxxsy this task has been masked as done:
```
* Tests are updated or added as necessary.
```
but saw no changes to the test code. Does it mean that these changes don't have to be tested?

**Comment by gytxxsy** [comment]
> @gytxxsy this task has been masked as done:
> 
> ```
> * Tests are updated or added as necessary.
> ```
> 
> but saw no changes to the test code. Does it mean that these changes don't have to be tested?

This PR is considered a fix for the existing functionality (referencing avahi's behavior) rather than adding new features, so I think it's not necessary to add new test cases.

**Comment by david-cermak** [comment]
> > @gytxxsy this task has been masked as done:
> > ```
> > * Tests are updated or added as necessary.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but saw no changes to the test code. Does it mean that these changes don't have to be tested?
> 
> @david-cermak This PR is considered a fix for the existing functionality (referencing avahi's behavior) rather than adding new features, so I think it's not necessary to add new test cases.

Thanks for explaining! LGTM!

**Review by david-cermak — APPROVED** [review]

**Comment by gytxxsy** [comment]
@david-cermak 
Do you have any plans to bump the version soon? I think this PR is a meaningful fix and needs to be included in the latest version.

**Pull request merged**
